#!/usr/bin/env node
/**
 * TEA UI — font build.
 *
 * `fonts.css` is a **pass-through**, not a Tailwind build. Tailwind would inline
 * the declarations but leave the `url(./files/*.woff2)` references unresolved,
 * and a stylesheet whose font URLs point at nothing renders in a fallback face
 * with no error at all — the most common way a "self-hosted fonts" setup quietly
 * stops self-hosting.
 *
 * So the three `@fontsource` stylesheets are concatenated verbatim and their
 * `files/` directories are copied next to the result. The relative URLs then
 * resolve, and the output is byte-identical to what `@fontsource` ships.
 */
import { cp, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(root, "packages/tokens/dist");
const filesOut = resolve(outDir, "files");

const FAMILIES = [
  "@fontsource-variable/jost",
  "@fontsource-variable/jetbrains-mono",
  "@fontsource/lilita-one",
];

async function main() {
  await mkdir(filesOut, { recursive: true });

  const parts = [
    "/* TEA UI — the typefaces. Generated by scripts/build-fonts.mjs; do not edit. */",
  ];

  for (const family of FAMILIES) {
    const packageDir = resolve(root, "node_modules", family);
    let indexFile;
    try {
      indexFile = resolve(packageDir, "index.css");
    } catch {
      /* unreachable, kept for clarity */
    }

    let css;
    try {
      css = await readFile(indexFile, "utf8");
    } catch {
      console.error(`[tea-ui] ${family} is not installed. Run: npm install -w @tea-ui/tokens ${FAMILIES.join(" ")}`);
      process.exitCode = 1;
      return;
    }

    parts.push(css);

    // The family ships its font binaries in a sibling `files/` directory. Two
    // of the three families use the same directory name, so merging is fine:
    // the filenames are prefixed with the family.
    const filesDir = resolve(packageDir, "files");
    const entries = await readdir(filesDir).catch(() => []);
    for (const entry of entries) {
      await cp(resolve(filesDir, entry), resolve(filesOut, entry), { force: true });
    }
  }

  await writeFile(resolve(outDir, "fonts.css"), `${parts.join("\n")}\n`, "utf8");
  const binaries = (await readdir(filesOut)).length;
  console.log(`[tea-ui] fonts.css written with ${binaries} font binaries.`);
}

await main();
